### PR TITLE
PBM-596: Azure Blob Storage support

### PR DESCRIPTION
**Pull request by dAdAbird**
I've also removed redundant method Files() from the storage interface. It just bloated an interface without any reason. All its functionality should be done on the user side.

https://jira.percona.com/browse/PBM-596

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| Restore on new cluster mongodb 3.6 | passed |
| Restore on new cluster mongodb 4.0 | passed |
| Restore on new cluster mongodb 4.2 | passed |
| Sharded cluster mongodb 3.6 | failed |
| Non-sharded replicaset mongodb 3.6 | failed |
| Sharded cluster mongodb 4.0 | failed |
| Non-sharded replicaset mongodb 4.0 | failed |
| Sharded cluster mongodb 4.2 | failed |
| Non-sharded replicaset mongodb 4.2 | failed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| Non-sharded replicaset mongodb 4.0 | passed |
| Non-sharded replicaset mongodb 3.6 | passed |
| Non-sharded replicaset mongodb 4.2 | passed |
| Sharded cluster mongodb 4.0 | passed |
| Restore on new cluster mongodb 4.0 | passed |
| Sharded cluster mongodb 4.2 | passed |
| Sharded cluster mongodb 3.6 | failed |
| Restore on new cluster mongodb 3.6 | passed |
| Restore on new cluster mongodb 4.2 | passed |

**Review by akira-kurogane — APPROVED** [review]
LGTM Andrew-san!

**Pull request merged**
