### PR TITLE
[PBM-1007] selective backup/restore for sharded collections

### PR DESCRIPTION
**Pull request by defbin**
This PR brings Selective Backup and Selective Restore for sharded collections.

A sharded collection is made of collections on one or more replsets with a subset of documents. On configsvr, there are collections with router configuration that describes what documents on which shards are. For example, mongos use these collections to build queries to specific shard(s) only depending on the shard key value in the original client query.

Router config collections:
- __config.databases__: contains documents that describe a database and its primary shard (for example, all non-sharded collections are entirely stored on that shard only)
- __config.collections__: contains documents that describe a sharded collection (for example, UUID used in _config.chunks_ since v5.0)
- __config.chunks__: contains documents that describe on which shard a shard key range of a collection is stored

[these collections and similar are also cached on each shard but are updating eventually after a restore]

In this PR, the only required documents for the collections are backing up and restoring. PBM saves full oplog range during backup time but still, replays ops selectively.
It does not remove existing documents for other databases/collections/chunks but removes all chunks of selected collection(s) before restore. Existing documents in _config.database_ and _config.collections_ are replaced, non-existing - inserted.

Limits:
- Sharded timeseries is not supported (but non-sharded timeseries already does).
- Selective PITR is not supported. Only snapshot restore (it still does oplog replay underly but no chunk split/move in oplog because of disabled balancer/auto splitter during backup)

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| New cluster psmdb 4.4 | failed | - |
| New cluster psmdb 4.2 | failed | - |
| New cluster psmdb 5.0 | failed | - |
| New cluster psmdb 6.0 | failed | - |
| Sharded psmdb 4.2 | failed | passed |
| Sharded psmdb 4.4 | failed | passed |
| Non-sharded psmdb 4.4 | passed | passed |
| Non-sharded psmdb 4.2 | failed | passed |
| Non-sharded psmdb 5.0 | passed | passed |
| Non-sharded psmdb 6.0 | failed | passed |
| Single-node psmdb 4.2 | passed | passed |
| Sharded psmdb 5.0 | failed | passed |
| Single-node psmdb 4.4 | failed | passed |
| Single-node psmdb 5.0 | passed | passed |
| Single-node psmdb 6.0 | passed | passed |
| Sharded psmdb 6.0 | failed | failed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| Sharded psmdb 4.2 | failed | failed |
| New cluster psmdb 4.2 | failed | - |
| New cluster psmdb 4.4 | failed | - |
| New cluster psmdb 5.0 | failed | - |
| New cluster psmdb 6.0 | failed | - |
| Non-sharded psmdb 4.2 | failed | failed |
| Non-sharded psmdb 4.4 | failed | failed |
| Non-sharded psmdb 5.0 | failed | failed |
| Single-node psmdb 4.2 | failed | failed |
| Non-sharded psmdb 6.0 | failed | failed |
| Single-node psmdb 4.4 | failed | failed |
| Single-node psmdb 5.0 | failed | failed |
| Single-node psmdb 6.0 | failed | failed |
| Sharded psmdb 4.4 | failed | failed |
| Sharded psmdb 5.0 | failed | failed |
| Sharded psmdb 6.0 | failed | failed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| Sharded psmdb 4.2 | failed | failed |
| New cluster psmdb 4.2 | failed | - |
| New cluster psmdb 4.4 | failed | - |
| New cluster psmdb 5.0 | failed | - |
| New cluster psmdb 6.0 | failed | - |
| Sharded psmdb 4.4 | failed | failed |
| Non-sharded psmdb 4.2 | failed | failed |
| Non-sharded psmdb 5.0 | failed | failed |
| Sharded psmdb 5.0 | failed | failed |
| Sharded psmdb 6.0 | failed | failed |
| Non-sharded psmdb 6.0 | failed | failed |
| Single-node psmdb 4.2 | failed | failed |
| Non-sharded psmdb 4.4 | failed | failed |
| Single-node psmdb 4.4 | failed | failed |
| Single-node psmdb 5.0 | failed | failed |
| Single-node psmdb 6.0 | failed | failed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| New cluster psmdb 4.2 | failed | - |
| New cluster psmdb 4.4 | failed | - |
| Sharded psmdb 4.2 | failed | failed |
| New cluster psmdb 6.0 | failed | - |
| New cluster psmdb 5.0 | failed | - |
| Sharded psmdb 4.4 | failed | failed |
| Non-sharded psmdb 4.2 | failed | failed |
| Non-sharded psmdb 4.4 | failed | failed |
| Non-sharded psmdb 5.0 | failed | failed |
| Non-sharded psmdb 6.0 | failed | failed |
| Single-node psmdb 4.2 | failed | failed |
| Single-node psmdb 4.4 | failed | failed |
| Single-node psmdb 5.0 | failed | failed |
| Single-node psmdb 6.0 | failed | failed |
| Sharded psmdb 6.0 | failed | failed |
| Sharded psmdb 5.0 | failed | failed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| New cluster psmdb 4.4 | failed | - |
| New cluster psmdb 4.2 | failed | - |
| New cluster psmdb 5.0 | failed | - |
| New cluster psmdb 6.0 | failed | - |
| Non-sharded psmdb 4.4 | passed | passed |
| Non-sharded psmdb 4.2 | passed | failed |
| Sharded psmdb 4.4 | failed | passed |
| Sharded psmdb 4.2 | failed | failed |
| Non-sharded psmdb 5.0 | passed | passed |
| Non-sharded psmdb 6.0 | passed | passed |
| Single-node psmdb 4.2 | passed | failed |
| Sharded psmdb 5.0 | failed | passed |
| Sharded psmdb 6.0 | failed | failed |
| Single-node psmdb 4.4 | failed | passed |
| Single-node psmdb 6.0 | passed | passed |
| Single-node psmdb 5.0 | passed | passed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| New cluster psmdb 4.2 | failed | - |
| Sharded psmdb 4.2 | failed | failed |
| Sharded psmdb 4.4 | failed | passed |
| Sharded psmdb 5.0 | failed | failed |
| Sharded psmdb 6.0 | failed | failed |
| New cluster psmdb 4.4 | failed | - |
| New cluster psmdb 5.0 | failed | - |
| Non-sharded psmdb 4.2 | failed | failed |
| New cluster psmdb 6.0 | failed | - |
| Non-sharded psmdb 4.4 | passed | passed |
| Non-sharded psmdb 5.0 | passed | passed |
| Non-sharded psmdb 6.0 | passed | passed |
| Single-node psmdb 4.2 | passed | failed |
| Single-node psmdb 4.4 | passed | passed |
| Single-node psmdb 5.0 | passed | passed |
| Single-node psmdb 6.0 | failed | passed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| New cluster psmdb 4.2 | failed | - |
| New cluster psmdb 5.0 | failed | - |
| New cluster psmdb 4.4 | failed | - |
| New cluster psmdb 6.0 | failed | - |
| Non-sharded psmdb 4.2 | passed | failed |
| Non-sharded psmdb 4.4 | passed | passed |
| Sharded psmdb 4.4 | failed | passed |
| Sharded psmdb 4.2 | failed | failed |
| Non-sharded psmdb 5.0 | passed | passed |
| Non-sharded psmdb 6.0 | failed | failed |
| Single-node psmdb 4.4 | failed | passed |
| Sharded psmdb 5.0 | failed | passed |
| Single-node psmdb 4.2 | failed | failed |
| Single-node psmdb 5.0 | failed | passed |
| Sharded psmdb 6.0 | failed | failed |
| Single-node psmdb 6.0 | failed | passed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| New cluster psmdb 4.4 | failed | - |
| New cluster psmdb 4.2 | failed | - |
| New cluster psmdb 5.0 | failed | - |
| Sharded psmdb 4.2 | failed | failed |
| New cluster psmdb 6.0 | failed | - |
| Non-sharded psmdb 4.2 | failed | failed |
| Sharded psmdb 4.4 | failed | passed |
| Non-sharded psmdb 4.4 | failed | failed |
| Non-sharded psmdb 5.0 | failed | passed |
| Sharded psmdb 5.0 | failed | failed |
| Non-sharded psmdb 6.0 | passed | failed |
| Single-node psmdb 4.2 | passed | failed |
| Single-node psmdb 4.4 | passed | failed |
| Single-node psmdb 5.0 | failed | failed |
| Single-node psmdb 6.0 | passed | failed |
| Sharded psmdb 6.0 | failed | failed |

**Review by dAdAbird — COMMENTED** [review]
Put on, please, a commit message elaborating on the changes and bringing some context. What from where and why should be filtered out? What scenarios/setups aren't supported (and why)?  etc

**Review by dAdAbird — APPROVED** [review]

**Pull request merged**
