### PR TITLE
PBM-688: CI tests for PBM-617

### PR DESCRIPTION
**Pull request by dAdAbird**
related https://jira.percona.com/browse/PBM-617

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| Sharded cluster mongodb 3.6 | failed |
| Sharded cluster mongodb 4.0 | failed |
| Sharded cluster mongodb 4.2 | failed |
| Restore on new cluster mongodb 3.6 | passed |
| Restore on new cluster mongodb 4.0 | passed |
| Restore on new cluster mongodb 4.2 | failed |
| Non-sharded replicaset mongodb 4.2 | failed |
| Non-sharded replicaset mongodb 3.6 | failed |
| Non-sharded replicaset mongodb 4.0 | failed |
| Single-node replicaset mongodb 4.0 | failed |
| Single-node replicaset mongodb 3.6 | failed |
| Single-node replicaset mongodb 4.2 | failed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| Sharded cluster mongodb 3.6 | passed |
| Sharded cluster mongodb 4.0 | passed |
| Sharded cluster mongodb 4.2 | passed |
| Restore on new cluster mongodb 3.6 | failed |
| Non-sharded replicaset mongodb 3.6 | passed |
| Restore on new cluster mongodb 4.2 | passed |
| Restore on new cluster mongodb 4.0 | passed |
| Non-sharded replicaset mongodb 4.2 | passed |
| Non-sharded replicaset mongodb 4.0 | failed |
| Single-node replicaset mongodb 3.6 | passed |
| Single-node replicaset mongodb 4.0 | passed |
| Single-node replicaset mongodb 4.2 | passed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| Sharded cluster mongodb 3.6 | failed |
| Sharded cluster mongodb 4.0 | failed |
| Sharded cluster mongodb 4.2 | failed |
| Restore on new cluster mongodb 3.6 | passed |
| Non-sharded replicaset mongodb 4.0 | failed |
| Restore on new cluster mongodb 4.0 | passed |
| Restore on new cluster mongodb 4.2 | passed |
| Non-sharded replicaset mongodb 3.6 | failed |
| Non-sharded replicaset mongodb 4.2 | failed |
| Single-node replicaset mongodb 3.6 | failed |
| Single-node replicaset mongodb 4.0 | failed |
| Single-node replicaset mongodb 4.2 | failed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| Sharded cluster mongodb 3.6 | failed |
| Sharded cluster mongodb 4.2 | failed |
| Sharded cluster mongodb 4.0 | failed |
| Restore on new cluster mongodb 3.6 | passed |
| Restore on new cluster mongodb 4.0 | passed |
| Restore on new cluster mongodb 4.2 | passed |
| Non-sharded replicaset mongodb 3.6 | failed |
| Non-sharded replicaset mongodb 4.0 | failed |
| Non-sharded replicaset mongodb 4.2 | failed |
| Single-node replicaset mongodb 3.6 | failed |
| Single-node replicaset mongodb 4.0 | failed |
| Single-node replicaset mongodb 4.2 | failed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| Sharded cluster mongodb 3.6 | failed |
| Sharded cluster mongodb 4.0 | failed |
| Sharded cluster mongodb 4.2 | failed |
| Restore on new cluster mongodb 4.2 | passed |
| Restore on new cluster mongodb 3.6 | passed |
| Restore on new cluster mongodb 4.0 | passed |
| Non-sharded replicaset mongodb 3.6 | failed |
| Non-sharded replicaset mongodb 4.0 | failed |
| Non-sharded replicaset mongodb 4.2 | failed |
| Single-node replicaset mongodb 3.6 | failed |
| Single-node replicaset mongodb 4.0 | failed |
| Single-node replicaset mongodb 4.2 | failed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| Sharded cluster mongodb 3.6 | failed |
| Sharded cluster mongodb 4.0 | failed |
| Sharded cluster mongodb 4.2 | failed |
| Restore on new cluster mongodb 3.6 | passed |
| Restore on new cluster mongodb 4.0 | passed |
| Restore on new cluster mongodb 4.2 | passed |
| Non-sharded replicaset mongodb 3.6 | failed |
| Non-sharded replicaset mongodb 4.2 | failed |
| Single-node replicaset mongodb 3.6 | failed |
| Non-sharded replicaset mongodb 4.0 | failed |
| Single-node replicaset mongodb 4.0 | failed |
| Single-node replicaset mongodb 4.2 | failed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| Sharded cluster mongodb 3.6 | failed |
| Sharded cluster mongodb 4.0 | failed |
| Sharded cluster mongodb 4.2 | failed |
| Restore on new cluster mongodb 3.6 | passed |
| Non-sharded replicaset mongodb 4.0 | failed |
| Restore on new cluster mongodb 4.0 | failed |
| Non-sharded replicaset mongodb 3.6 | failed |
| Restore on new cluster mongodb 4.2 | passed |
| Single-node replicaset mongodb 3.6 | failed |
| Non-sharded replicaset mongodb 4.2 | failed |
| Single-node replicaset mongodb 4.0 | failed |
| Single-node replicaset mongodb 4.2 | failed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| Sharded cluster mongodb 3.6 | failed |
| Sharded cluster mongodb 4.0 | failed |
| Sharded cluster mongodb 4.2 | failed |
| Restore on new cluster mongodb 3.6 | passed |
| Restore on new cluster mongodb 4.0 | passed |
| Non-sharded replicaset mongodb 4.0 | failed |
| Non-sharded replicaset mongodb 3.6 | failed |
| Restore on new cluster mongodb 4.2 | passed |
| Non-sharded replicaset mongodb 4.2 | failed |
| Single-node replicaset mongodb 3.6 | failed |
| Single-node replicaset mongodb 4.0 | failed |
| Single-node replicaset mongodb 4.2 | failed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| Sharded cluster mongodb 3.6 | failed |
| Sharded cluster mongodb 4.0 | failed |
| Sharded cluster mongodb 4.2 | failed |
| Restore on new cluster mongodb 3.6 | passed |
| Non-sharded replicaset mongodb 4.0 | failed |
| Restore on new cluster mongodb 4.0 | passed |
| Non-sharded replicaset mongodb 3.6 | failed |
| Restore on new cluster mongodb 4.2 | passed |
| Single-node replicaset mongodb 4.0 | failed |
| Single-node replicaset mongodb 3.6 | failed |
| Non-sharded replicaset mongodb 4.2 | failed |
| Single-node replicaset mongodb 4.2 | failed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| Sharded cluster mongodb 3.6 | failed |
| Sharded cluster mongodb 4.0 | failed |
| Sharded cluster mongodb 4.2 | failed |
| Restore on new cluster mongodb 3.6 | passed |
| Restore on new cluster mongodb 4.0 | passed |
| Restore on new cluster mongodb 4.2 | failed |
| Non-sharded replicaset mongodb 3.6 | failed |
| Single-node replicaset mongodb 3.6 | failed |
| Non-sharded replicaset mongodb 4.2 | failed |
| Non-sharded replicaset mongodb 4.0 | failed |
| Single-node replicaset mongodb 4.2 | failed |
| Single-node replicaset mongodb 4.0 | failed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| Sharded cluster mongodb 3.6 | failed |
| Sharded cluster mongodb 4.0 | failed |
| Sharded cluster mongodb 4.2 | failed |
| Restore on new cluster mongodb 4.0 | passed |
| Restore on new cluster mongodb 3.6 | passed |
| Non-sharded replicaset mongodb 3.6 | failed |
| Restore on new cluster mongodb 4.2 | passed |
| Non-sharded replicaset mongodb 4.0 | failed |
| Non-sharded replicaset mongodb 4.2 | failed |
| Single-node replicaset mongodb 3.6 | failed |
| Single-node replicaset mongodb 4.0 | failed |
| Single-node replicaset mongodb 4.2 | failed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| Non-sharded replicaset mongodb 3.6 | failed |
| Non-sharded replicaset mongodb 4.0 | failed |
| Non-sharded replicaset mongodb 4.2 | failed |
| Restore on new cluster mongodb 4.0 | passed |
| Restore on new cluster mongodb 3.6 | passed |
| Restore on new cluster mongodb 4.2 | passed |
| Single-node replicaset mongodb 3.6 | failed |
| Sharded cluster mongodb 3.6 | failed |
| Sharded cluster mongodb 4.0 | failed |
| Sharded cluster mongodb 4.2 | failed |
| Single-node replicaset mongodb 4.0 | failed |
| Single-node replicaset mongodb 4.2 | failed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| Sharded cluster mongodb 3.6 | failed |
| Sharded cluster mongodb 4.0 | failed |
| Sharded cluster mongodb 4.2 | failed |
| Restore on new cluster mongodb 4.2 | failed |
| Restore on new cluster mongodb 3.6 | passed |
| Restore on new cluster mongodb 4.0 | passed |
| Non-sharded replicaset mongodb 4.0 | failed |
| Non-sharded replicaset mongodb 3.6 | failed |
| Non-sharded replicaset mongodb 4.2 | failed |
| Single-node replicaset mongodb 3.6 | passed |
| Single-node replicaset mongodb 4.2 | passed |
| Single-node replicaset mongodb 4.0 | passed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| Sharded cluster mongodb 3.6 | failed |
| Sharded cluster mongodb 4.0 | failed |
| Sharded cluster mongodb 4.2 | failed |
| Restore on new cluster mongodb 3.6 | passed |
| Restore on new cluster mongodb 4.0 | passed |
| Restore on new cluster mongodb 4.2 | passed |
| Non-sharded replicaset mongodb 3.6 | passed |
| Non-sharded replicaset mongodb 4.0 | failed |
| Single-node replicaset mongodb 3.6 | passed |
| Non-sharded replicaset mongodb 4.2 | failed |
| Single-node replicaset mongodb 4.0 | passed |
| Single-node replicaset mongodb 4.2 | passed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| Restore on new cluster mongodb 3.6 | passed |
| Sharded cluster mongodb 3.6 | failed |
| Sharded cluster mongodb 4.0 | failed |
| Sharded cluster mongodb 4.2 | failed |
| Non-sharded replicaset mongodb 3.6 | passed |
| Restore on new cluster mongodb 4.0 | passed |
| Restore on new cluster mongodb 4.2 | passed |
| Non-sharded replicaset mongodb 4.0 | passed |
| Non-sharded replicaset mongodb 4.2 | failed |
| Single-node replicaset mongodb 3.6 | passed |
| Single-node replicaset mongodb 4.0 | passed |
| Single-node replicaset mongodb 4.2 | passed |

**Review by akira-kurogane — APPROVED** [review]
LGTM

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| Restore on new cluster mongodb 3.6 | passed |
| Sharded cluster mongodb 3.6 | passed |
| Sharded cluster mongodb 4.0 | failed |
| Sharded cluster mongodb 4.2 | passed |
| Restore on new cluster mongodb 4.0 | passed |
| Restore on new cluster mongodb 4.2 | passed |
| Non-sharded replicaset mongodb 3.6 | failed |
| Non-sharded replicaset mongodb 4.0 | failed |
| Non-sharded replicaset mongodb 4.2 | failed |
| Single-node replicaset mongodb 3.6 | passed |
| Single-node replicaset mongodb 4.0 | passed |
| Single-node replicaset mongodb 4.2 | passed |

**Pull request merged**
