### PR TITLE
PBM-875: concurrent download

### PR DESCRIPTION
**Pull request by dAdAbird**
Each object can be downloaded concurrently in chunks. If a download of a
chunk has failed it will be retried a certain amount of time before
returning with an error.
It starts with the number of workers equal to the concurrency setting. Each
worker takes a task with a needed object range (chunk) and downloads it into
a part (span) of its memory buffer (arena). Returns an io.ReaderCloser
object with the content of the span. And gets a next free span to download
the next chunk.
The consumer closing io.ReaderCloser marks the respective span as free reuse.
An arenas pool is created with the `Download` object and reused for every next
downloaded object.
Although the object's chunks can be downloaded concurrently, they should be
streamed to the consumer sequentially (objects usually are compressed, hence
the consumer can't be an oi.Seeker). Therefore if a downloaded span's range
is out of order (preceding chunks aren't downloaded yet) it is added to the
heap structure (`chunksQueue`) and waits for its queue to be passed to
the consumer.
The max size the buffer of would be `arenaSize * concurrency`. Where
`arenaSize` is `spanSize * spansInArena`. It doesn't mean all of this size
would be allocated as some of the span slots may remain unused.

Download arena (bytes slice) is split into spans (represented by `dpsan`)
whose size should be equal to download chunks. `dspan` implements io.Wrire
and io.ReaderCloser interface. Close() marks the span as free to use
(download another chunk).
Free/busy spans list is managed via lock-free bitmap index.

New config options:
```
restore:
 ...
	// NumDownloadWorkers sets the num of goroutine would be requesting chunks
	// during the download. By default, it's set to GOMAXPROCS.
	// Default: num of CPU cores
	numDownloadWorkers int
	// MaxDownloadBufferMb sets the max size of the in-memory buffer that is used
	// to download files from the storage.
	// Default: 0 - `numDownloadWorkers * downloadChunkMb * 16`
	maxDownloadBufferMb int
	// Default: 32 (32Mb)
	downloadChunkMb int 
```

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| New cluster psmdb 4.2 | failed | - |
| New cluster psmdb 4.4 | failed | - |
| New cluster psmdb 5.0 | failed | - |
| Non-sharded psmdb 4.2 | failed | failed |
| Sharded psmdb 4.2 | failed | failed |
| Sharded psmdb 4.4 | failed | failed |
| Non-sharded psmdb 4.4 | failed | failed |
| Sharded psmdb 5.0 | failed | failed |
| Non-sharded psmdb 5.0 | failed | failed |
| Single-node psmdb 4.2 | failed | failed |
| Single-node psmdb 4.4 | failed | failed |
| Single-node psmdb 5.0 | failed | failed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| New cluster psmdb 4.2 | passed | - |
| New cluster psmdb 4.4 | passed | - |
| New cluster psmdb 5.0 | passed | - |
| Sharded psmdb 4.2 | passed | failed |
| Non-sharded psmdb 4.4 | passed | failed |
| Non-sharded psmdb 4.2 | failed | failed |
| Sharded psmdb 5.0 | failed | failed |
| Sharded psmdb 4.4 | failed | failed |
| Non-sharded psmdb 5.0 | passed | passed |
| Single-node psmdb 4.2 | passed | failed |
| Single-node psmdb 5.0 | passed | passed |
| Single-node psmdb 4.4 | passed | failed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| Sharded psmdb 4.2 | failed | failed |
| Sharded psmdb 4.4 | failed | failed |
| Sharded psmdb 5.0 | failed | passed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| New cluster psmdb 4.2 | failed | - |
| New cluster psmdb 4.4 | passed | - |
| New cluster psmdb 5.0 | passed | - |
| Non-sharded psmdb 4.2 | failed | failed |
| Non-sharded psmdb 4.4 | passed | passed |
| Non-sharded psmdb 5.0 | passed | passed |
| Single-node psmdb 4.2 | failed | failed |
| Single-node psmdb 4.4 | failed | passed |
| Single-node psmdb 5.0 | passed | passed |
| Sharded psmdb 4.4 | failed | passed |
| Sharded psmdb 4.2 | failed | failed |
| Sharded psmdb 5.0 | failed | passed |

**Review by defbin — DISMISSED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| New cluster psmdb 4.4 | failed | - |
| New cluster psmdb 5.0 | failed | - |
| Sharded psmdb 4.2 | failed | failed |
| New cluster psmdb 4.2 | failed | - |
| Non-sharded psmdb 4.2 | failed | failed |
| Sharded psmdb 4.4 | failed | failed |
| Sharded psmdb 5.0 | failed | failed |
| New cluster psmdb 6.0 | failed | - |
| Non-sharded psmdb 4.4 | failed | failed |
| Non-sharded psmdb 5.0 | failed | failed |
| Non-sharded psmdb 6.0 | failed | failed |
| Sharded psmdb 6.0 | failed | failed |
| Single-node psmdb 4.2 | failed | failed |
| Single-node psmdb 4.4 | failed | failed |
| Single-node psmdb 5.0 | failed | failed |
| Single-node psmdb 6.0 | failed | failed |

**Review by defbin — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| Single-node psmdb 4.2 | failed | passed |
| New cluster psmdb 6.0 | failed | - |
| Sharded psmdb 4.4 | failed | passed |
| Single-node psmdb 4.4 | failed | passed |
| New cluster psmdb 5.0 | passed | - |
| Non-sharded psmdb 4.2 | passed | passed |
| Non-sharded psmdb 6.0 | failed | passed |
| Non-sharded psmdb 4.4 | failed | passed |
| Sharded psmdb 5.0 | failed | passed |
| Non-sharded psmdb 5.0 | failed | passed |
| Sharded psmdb 6.0 | failed | failed |
| Sharded psmdb 4.2 | failed | failed |
| Single-node psmdb 5.0 | failed | passed |
| New cluster psmdb 4.4 | passed | - |
| Single-node psmdb 6.0 | failed | passed |
| New cluster psmdb 4.2 | passed | - |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| New cluster psmdb 4.4 | passed | - |
| New cluster psmdb 6.0 | failed | - |
| New cluster psmdb 5.0 | passed | - |
| New cluster psmdb 4.2 | passed | - |
| Sharded psmdb 4.2 | failed | passed |
| Sharded psmdb 4.4 | failed | passed |
| Sharded psmdb 5.0 | failed | passed |
| Sharded psmdb 6.0 | failed | failed |
| Non-sharded psmdb 4.2 | failed | passed |
| Non-sharded psmdb 4.4 | passed | passed |
| Single-node psmdb 4.2 | passed | passed |
| Non-sharded psmdb 6.0 | passed | passed |
| Non-sharded psmdb 5.0 | passed | passed |
| Single-node psmdb 5.0 | failed | passed |
| Single-node psmdb 6.0 | passed | passed |
| Single-node psmdb 4.4 | passed | failed |

**Pull request merged**
