### PR TITLE
PBM-1332 Fix: failed to delete the history backup data

### PR DESCRIPTION
**Pull request by Cookiery**
Ticket: https://perconadev.atlassian.net/browse/PBM-1332

I've encountered the same problem as the ticket above, I debugged it and found that it's because the DeleteObject method doesn't support deleting directory Objects.

BTW, thanks for your contributions, it's a great tool to use!

### CODE REVIEW

**Comment by Cookiery** [comment]
Also corrected a few typo errors

**Comment by Cookiery** [comment]
Hi @defbin , could you take a look my pull request, thanks!

**Comment by defbin** [comment]
hi @Cookiery. thank you for your contribution.

I tested your branch with MinIO server, and it does not delete the `filelist.pbm` file. does it work for you?

**Comment by Cookiery** [comment]
hi @defbin . thanks for your feedback. 
Sorry, I was so focused on deleting directories that I forgot about the .pbm.json file, I'll fix that.

**Comment by defbin** [comment]
We don't need this logic. Just specify the file explicitly, like in https://github.com/percona/percona-backup-mongodb/pull/965/files, and the backup dir will be deleted at the end.

Please make it simple and just enough to fix the issue. You are free to copy changes from the alternative PR (I'll close it in favor of yours)

**Comment by Cookiery** [comment]
I think it would be better to support deleting directories and files directly in the `Delete`function?

**Comment by Cookiery** [comment]
The problem is that specifying a file doesn't delete the directory on S3, we need to list all files to delete it.

**Comment by Cookiery** [comment]
Hi @defbin , I can delete the .pbm.json file with this function.
```
func main() {
	endpoint := ""
	accessKey := ""
	secretKey := ""

	sess, err := session.NewSession(&aws.Config{
		Region:           aws.String("us-east-1"),
		Endpoint:         aws.String(endpoint),
		S3ForcePathStyle: aws.Bool(true),
		Credentials:      credentials.NewStaticCredentials(accessKey, secretKey, ""),
	})

	if err != nil {
		fmt.Println("Failed to create session:", err)
		return
	}

	svc := s3.New(sess)

	bucket := "mongodb-backup"
	prefix := ""
	name := "2024-06-27T18:59:51Z.pbm.json"

	allObjects := []*s3.ObjectIdentifier{}

	err = svc.ListObjectsV2Pages(&s3.ListObjectsV2Input{
		Bucket: aws.String(bucket),
		Prefix: aws.String(path.Join(prefix, name)),
	}, func(page *s3.ListObjectsV2Output, lastPage bool) bool {
		for _, obj := range page.Contents {
			allObjects = append(allObjects, &s3.ObjectIdentifier{
				Key: aws.String(*obj.Key),
			})
		}
		return !lastPage
	})

	if err != nil {
		fmt.Println("Failed to list objects:", err)
		return
	}

	if len(allObjects) == 0 {
		fmt.Println("No objects found to delete")
		return
	}

	// Batch delete
	var objectsToDelete []*s3.ObjectIdentifier
	for _, object := range allObjects {
		objectsToDelete = append(objectsToDelete, &s3.ObjectIdentifier{
			Key: object.Key,
		})
	}

	_, err = svc.DeleteObjects(&s3.DeleteObjectsInput{
		Bucket: aws.String(bucket),
		Delete: &s3.Delete{
			Objects: objectsToDelete,
			Quiet:   aws.Bool(true),
		},
	})

	if err != nil {
		fmt.Println("Failed to delete objects:", err)
		return
	}

	// Confirm delete
	for _, object := range objectsToDelete {
		err = svc.WaitUntilObjectNotExists(&s3.HeadObjectInput{
			Bucket: aws.String(bucket),
			Key:    object.Key,
		})

		if err != nil {
			fmt.Printf("Error occurred while waiting for object %s to be deleted: %v\n", aws.StringValue(object.Key), err)
		} else {
			fmt.Printf("Object %s deleted successfully\n", aws.StringValue(object.Key))
		}
	}
}
```

**Comment by defbin** [comment]
did you tried the https://github.com/percona/percona-backup-mongodb/pull/965 ?

**Comment by defbin** [comment]
I mean, did you try to delete a backup with that code changes only? What problem did you meet?

**Comment by Cookiery** [comment]
I have the same problem as this ticket, that is, when deleting the backup file, none of the S3 directory files are deleted. 

https://perconadev.atlassian.net/browse/PBM-1332

image

**Comment by Cookiery** [comment]
It's not a complicated function, just list all the objects and batch delete them.

**Comment by defbin** [comment]
Please test the `defbin/PBM-1332` branch. It must resolve the issue. I tested the branch with MinIO and AWS S3 - and it works as expected.

PBM deletes files individually for a backup. The original issue is that one file is missing (which was added in a recent release).

Your PR adds new/extra logic (and network calls per file), which does not resolve the issue (I haven't found a practical reason to accept your changes). Did you analyze the impact of your changes? The Delete() method is called in many places. Have you reviewed each one?

**Comment by Cookiery** [comment]
Thanks @defbin , you can close this PR.

**Pull request closed without merging**
