### PR TITLE
Add Amazon S3 backup folder to bucket.

### PR DESCRIPTION
**Pull request by drafil**
Added Amazon S3 backup folder to filesystem path. This allows a better backup separation by folder inside the same bucket.

### CODE REVIEW

**Comment by it-percona** [comment]
[CLA assistant check](https://cla-assistant.percona.com:443/percona/percona-backup-mongodb?pullRequest=281) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-backup-mongodb?pullRequest=281) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: drafil<br/>:x: dcfilipescu<br/><hr/>**dcfilipescu** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-backup-mongodb?pullRequest=281) it.</sub>

**Comment by delgod** [comment]
@drafil could you please sign CLA ^^^

**Comment by drafil** [comment]
> @drafil could you please sign CLA ^^^

Hi @delgod, I have already did, it still shows the message that I have to sign it, but when I click on the link it says I have signed it...

**Review by dAdAbird — CHANGES_REQUESTED** [review]
HI,

Thank you for your contribution. It's a useful feature from our backlog.
But I suggest some design changes.
The folder shouldn't be taken from the `Filesystem` config section. If it relates to the S3 so it should in the S3 section. Also, despite rewriting the backup name allows to cut some corners it creates additional confusion and visual noise in the `pbm list` output or while referring to backup in `pbm restore`.

For the S3 a path should be a part of `bucket` config filed. E.g.:
```yaml
type: s3
s3:
    region: us-east-1
    bucket: my-bucket/path/to/subfolder
```
so it should be parsed before S3 request sending: everything before the first `/`  belongs to the bucket, the rest is the path. Keep in mind that `bucket: s3://mybucket/path` form should be considered as valid.

**Pull request closed without merging**
