### PR TITLE
PBM-864: correct pbm status and list commands

### PR DESCRIPTION
**Pull request by defbin**

### CODE REVIEW

**Review by dAdAbird — DISMISSED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| Single-node psmdb 4.4 | failed | failed |
| Non-sharded psmdb 4.4 | failed | failed |
| New cluster psmdb 5.0 | failed | - |
| Single-node psmdb 5.0 | failed | failed |
| Non-sharded psmdb 5.0 | failed | failed |
| Single-node psmdb 4.2 | failed | failed |
| Non-sharded psmdb 4.2 | failed | failed |
| New cluster psmdb 4.2 | passed | - |
| New cluster psmdb 4.4 | passed | - |
| Sharded psmdb 4.2 | failed | failed |
| Sharded psmdb 4.4 | failed | failed |
| Sharded psmdb 5.0 | failed | passed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| New cluster psmdb 4.2 | failed | - |
| New cluster psmdb 4.4 | failed | - |
| Sharded psmdb 4.2 | passed | failed |
| Sharded psmdb 4.4 | failed | failed |
| Sharded psmdb 5.0 | failed | failed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| Single-node psmdb 4.2 | passed | passed |
| Non-sharded psmdb 5.0 | failed | passed |
| Non-sharded psmdb 4.4 | passed | passed |
| Single-node psmdb 4.4 | passed | passed |
| Single-node psmdb 5.0 | failed | failed |
| New cluster psmdb 4.4 | passed | - |
| Non-sharded psmdb 4.2 | passed | passed |
| New cluster psmdb 5.0 | passed | - |
| New cluster psmdb 4.2 | passed | - |
| Sharded psmdb 4.2 | failed | failed |
| Sharded psmdb 4.4 | passed | failed |
| Sharded psmdb 5.0 | failed | passed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| New cluster psmdb 4.2 | failed | - |
| New cluster psmdb 4.4 | passed | - |
| New cluster psmdb 5.0 | passed | - |
| Non-sharded psmdb 4.2 | passed | passed |
| Non-sharded psmdb 4.4 | passed | passed |
| Non-sharded psmdb 5.0 | failed | passed |
| Single-node psmdb 4.4 | passed | passed |
| Single-node psmdb 4.2 | passed | passed |
| Single-node psmdb 5.0 | failed | passed |

**Pull request merged**
