### PR TITLE
PBM-632: Add JSON output for all cli commands

### PR DESCRIPTION
**Pull request by dAdAbird**
1. Add a JSON output option to all pbm cli commands. `-o json`/`--out=json`
2. For debugging purposes also add [hidden] `json-pretty` option for the `-o` flag. It intends JSON output to make it more readable.
3. If JSON output is set - all errors would be also formatted in JSON.
4. In the case of JSON output all commands in cli would be non-blocking. E.g. `pbm backup -o json` will return `{"name":"2021-07-15T16:55:26Z","storage":"s3://http://127.0.0.1:9000/bkt/pbm"}` after the input validation and successful command send. Not waiting for confirmation from agents. 
5. To `pbm status` command added flag:
```
-s, --sections=SECTIONS ...    Sections of status to display <cluster>/<pitr>/<running>/<backups>
```
Could be set several sections: `pbm status -s cluster -s backups`. If nothing is set - everything is to be displayed.

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| Sharded cluster mongodb 3.6 | failed |
| Sharded cluster mongodb 4.0 | failed |
| Sharded cluster mongodb 4.2 | failed |
| Non-sharded replicaset mongodb 3.6 | failed |
| Restore on new cluster mongodb 3.6 | passed |
| Restore on new cluster mongodb 4.2 | passed |
| Restore on new cluster mongodb 4.0 | passed |
| Single-node replicaset mongodb 3.6 | failed |
| Non-sharded replicaset mongodb 4.0 | failed |
| Single-node replicaset mongodb 4.2 | failed |
| Non-sharded replicaset mongodb 4.2 | failed |
| Single-node replicaset mongodb 4.0 | failed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| Restore on new cluster mongodb 3.6 | passed |
| Non-sharded replicaset mongodb 3.6 | failed |
| Restore on new cluster mongodb 4.0 | passed |
| Restore on new cluster mongodb 4.2 | passed |
| Sharded cluster mongodb 3.6 | failed |
| Sharded cluster mongodb 4.2 | failed |
| Sharded cluster mongodb 4.0 | failed |
| Non-sharded replicaset mongodb 4.0 | failed |
| Single-node replicaset mongodb 4.2 | failed |
| Non-sharded replicaset mongodb 4.2 | failed |
| Single-node replicaset mongodb 3.6 | failed |
| Single-node replicaset mongodb 4.0 | failed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| Sharded cluster mongodb 3.6 | failed |
| Sharded cluster mongodb 4.0 | failed |
| Sharded cluster mongodb 4.2 | failed |
| Restore on new cluster mongodb 3.6 | passed |
| Restore on new cluster mongodb 4.0 | passed |
| Non-sharded replicaset mongodb 3.6 | failed |
| Restore on new cluster mongodb 4.2 | passed |
| Non-sharded replicaset mongodb 4.0 | failed |
| Single-node replicaset mongodb 4.0 | failed |
| Single-node replicaset mongodb 3.6 | failed |
| Non-sharded replicaset mongodb 4.2 | failed |
| Single-node replicaset mongodb 4.2 | failed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| Sharded cluster mongodb 3.6 | failed |
| Sharded cluster mongodb 4.0 | failed |
| Sharded cluster mongodb 4.2 | failed |
| Restore on new cluster mongodb 4.0 | passed |
| Restore on new cluster mongodb 3.6 | passed |
| Non-sharded replicaset mongodb 4.0 | failed |
| Non-sharded replicaset mongodb 3.6 | failed |
| Restore on new cluster mongodb 4.2 | passed |
| Non-sharded replicaset mongodb 4.2 | failed |
| Single-node replicaset mongodb 3.6 | failed |
| Single-node replicaset mongodb 4.0 | failed |
| Single-node replicaset mongodb 4.2 | failed |

**Review by akira-kurogane — APPROVED** [review]
That was a big one, but it looks good to me.

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| Sharded cluster mongodb 3.6 | failed |
| Sharded cluster mongodb 4.0 | passed |
| Sharded cluster mongodb 4.2 | passed |
| Restore on new cluster mongodb 3.6 | passed |
| Non-sharded replicaset mongodb 3.6 | passed |
| Restore on new cluster mongodb 4.0 | passed |
| Restore on new cluster mongodb 4.2 | passed |
| Non-sharded replicaset mongodb 4.0 | failed |
| Single-node replicaset mongodb 3.6 | passed |
| Non-sharded replicaset mongodb 4.2 | failed |
| Single-node replicaset mongodb 4.0 | passed |
| Single-node replicaset mongodb 4.2 | passed |

**Pull request merged**
