### PR TITLE
feat: add aws IRSA credentials support

### PR DESCRIPTION
**Pull request by pastequo**
Hello,

In the continuity of this PR (https://github.com/percona/percona-backup-mongodb/pull/592), this PR adds support for IRSA

### CODE REVIEW

**Comment by gabeguz** [comment]
Any feedback on this MR?

**Comment by dAdAbird** [comment]
@pastequo, thanks for the contribution!
@gabeguz LGTM but we have to do some testing on our side. It probably gonna lend in the next release.

**Comment by stobias123** [comment]
+1 - would love to have this functionality instead of needing to generate creds for each instance

**Review by defbin — DISMISSED** [review]

**Review by sandraromanchenko — DISMISSED** [review]

**Comment by sandraromanchenko** [comment]
Tests are ok, we can merge after resolving the conflicts

**Review by dAdAbird — DISMISSED** [review]

**Comment by dAdAbird** [comment]
@pastequo can you resolve conflicts? And we gonna merge it. Thanks!

**Review by dAdAbird — APPROVED** [review]

**Pull request merged**
