### PR TITLE
PBM-818 fix: Oplog replay unique index

### PR DESCRIPTION
**Pull request by dAdAbird**

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| New cluster psmdb 4.2 | passed | - |
| Sharded psmdb 4.2 | failed | failed |
| Sharded psmdb 4.4 | failed | failed |
| Sharded psmdb 5.0 | failed | failed |
| New cluster psmdb 4.4 | passed | - |
| New cluster psmdb 5.0 | failed | - |
| Non-sharded psmdb 4.2 | passed | failed |
| Non-sharded psmdb 4.4 | failed | failed |
| Non-sharded psmdb 5.0 | failed | failed |
| Single-node psmdb 4.4 | failed | passed |
| Single-node psmdb 4.2 | failed | passed |
| Single-node psmdb 5.0 | failed | passed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| Sharded psmdb 4.2 | failed | failed |
| Sharded psmdb 4.4 | failed | failed |
| Sharded psmdb 5.0 | failed | failed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| Sharded psmdb 4.2 | failed | failed |
| New cluster psmdb 4.2 | passed | - |
| Sharded psmdb 5.0 | failed | failed |
| Sharded psmdb 4.4 | failed | failed |
| New cluster psmdb 4.4 | passed | - |
| Non-sharded psmdb 4.2 | passed | failed |
| New cluster psmdb 5.0 | passed | - |
| Non-sharded psmdb 5.0 | failed | passed |
| Single-node psmdb 4.4 | failed | passed |
| Non-sharded psmdb 4.4 | failed | passed |
| Single-node psmdb 5.0 | failed | passed |
| Single-node psmdb 4.2 | passed | passed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| Sharded psmdb 4.4 | failed | failed |
| Sharded psmdb 4.2 | failed | failed |
| New cluster psmdb 4.2 | passed | - |
| New cluster psmdb 5.0 | passed | - |
| New cluster psmdb 4.4 | passed | - |
| Non-sharded psmdb 5.0 | failed | passed |
| Sharded psmdb 5.0 | failed | failed |
| Single-node psmdb 4.2 | failed | passed |
| Non-sharded psmdb 4.2 | failed | failed |
| Single-node psmdb 4.4 | failed | passed |
| Non-sharded psmdb 4.4 | failed | passed |
| Single-node psmdb 5.0 | failed | passed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| New cluster psmdb 4.2 | failed | - |
| Sharded psmdb 4.2 | failed | failed |
| Sharded psmdb 4.4 | failed | failed |
| New cluster psmdb 4.4 | passed | - |
| Sharded psmdb 5.0 | failed | failed |
| New cluster psmdb 5.0 | failed | - |
| Non-sharded psmdb 4.2 | failed | failed |
| Non-sharded psmdb 4.4 | failed | passed |
| Single-node psmdb 4.2 | failed | passed |
| Non-sharded psmdb 5.0 | failed | passed |
| Single-node psmdb 4.4 | failed | passed |
| Single-node psmdb 5.0 | failed | passed |

**Review by defbin — APPROVED** [review]

**Pull request merged**
