### PR TITLE
PBM-788 Change pbm user in packages

### PR DESCRIPTION
**Pull request by adivinho**

### CODE REVIEW

**Review by defbin — APPROVED** [review]
lgtm

**Comment by defbin** [comment]
@adivinho can you please explain why to use mongod user/group?

**Review by defbin — CHANGES_REQUESTED** [review]
could you please resolve reviewdog comments?

**Comment by adivinho** [comment]
> @adivinho can you please explain why to use mongod user/group?
Screenshot 2022-03-22 at 09 23 24

**Comment by EvgeniyPatlan** [comment]
> could you please resolve reviewdog comments?

@defbin it is not good idea to rework the build script.
It is build team responsibility and we are checking it on our own. shellckeck recommendations are not always really correct. So please disable shellcheck for buildscript (at least for now)

**Review by defbin — APPROVED** [review]

**Pull request merged**
