### PR TITLE
Tests: use PSMDB mongo client for agent + add v6.0 

### PR DESCRIPTION
**Pull request by dAdAbird**
Changes mostly needed to be able to run PSMDB arm64 packages
Plus, add PSMDB v6.0 tests

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| Sharded psmdb 4.2 | failed | passed |
| New cluster psmdb 4.2 | passed | - |
| Sharded psmdb 4.4 | failed | passed |
| Sharded psmdb 5.0 | failed | passed |
| New cluster psmdb 4.4 | passed | - |
| Non-sharded psmdb 4.2 | passed | passed |
| Non-sharded psmdb 4.4 | passed | passed |
| New cluster psmdb 5.0 | passed | - |
| Sharded psmdb 6.0 | failed | failed |
| Non-sharded psmdb 5.0 | passed | passed |
| Single-node psmdb 4.2 | failed | passed |
| Non-sharded psmdb 6.0 | failed | passed |
| New cluster psmdb 6.0 | failed | - |
| Single-node psmdb 4.4 | failed | passed |
| Single-node psmdb 5.0 | passed | passed |
| Single-node psmdb 6.0 | failed | passed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| New cluster psmdb 4.2 | passed | - |
| Sharded psmdb 4.2 | failed | passed |
| Sharded psmdb 5.0 | failed | passed |
| Sharded psmdb 4.4 | failed | failed |
| Sharded psmdb 6.0 | failed | failed |
| New cluster psmdb 4.4 | passed | - |
| New cluster psmdb 6.0 | failed | - |
| Non-sharded psmdb 6.0 | failed | passed |
| Single-node psmdb 4.4 | failed | passed |
| Non-sharded psmdb 4.4 | failed | passed |
| Single-node psmdb 5.0 | failed | passed |
| Non-sharded psmdb 5.0 | failed | passed |
| Single-node psmdb 4.2 | failed | passed |
| Non-sharded psmdb 4.2 | failed | passed |
| New cluster psmdb 5.0 | passed | - |
| Single-node psmdb 6.0 | failed | passed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| Sharded psmdb 4.2 | failed | failed |
| Sharded psmdb 4.4 | failed | failed |
| Sharded psmdb 5.0 | failed | failed |
| Sharded psmdb 6.0 | failed | failed |
| New cluster psmdb 4.2 | failed | - |
| New cluster psmdb 4.4 | failed | - |
| New cluster psmdb 5.0 | failed | - |
| Non-sharded psmdb 4.2 | passed | passed |
| Non-sharded psmdb 4.4 | passed | passed |
| New cluster psmdb 6.0 | failed | - |
| Single-node psmdb 4.2 | failed | passed |
| Non-sharded psmdb 5.0 | passed | passed |
| Non-sharded psmdb 6.0 | passed | passed |
| Single-node psmdb 4.4 | passed | - |
| Single-node psmdb 6.0 | passed | - |
| Single-node psmdb 5.0 | passed | - |

**Review by defbin — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| New cluster psmdb 4.2 | passed | - |
| Sharded psmdb 4.2 | failed | passed |
| New cluster psmdb 4.4 | passed | - |
| Sharded psmdb 4.4 | failed | passed |
| New cluster psmdb 6.0 | failed | - |
| Sharded psmdb 5.0 | failed | passed |
| New cluster psmdb 5.0 | passed | - |
| Sharded psmdb 6.0 | failed | failed |
| Non-sharded psmdb 5.0 | failed | failed |
| Non-sharded psmdb 6.0 | failed | passed |
| Non-sharded psmdb 4.2 | failed | passed |
| Non-sharded psmdb 4.4 | failed | passed |
| Single-node psmdb 4.4 | passed | passed |
| Single-node psmdb 5.0 | failed | passed |
| Single-node psmdb 6.0 | failed | passed |
| Single-node psmdb 4.2 | passed | passed |

**Pull request merged**
