### PR TITLE
PBM tests. Avoid checking storage unless it's s3

### PR DESCRIPTION
**Pull request by sandraromanchenko**

### CODE REVIEW

**Comment by boris-ilijic** [comment]
@sandraromanchenko In general I am fine with this change, but why we are skipping Azure and FS ?

**Comment by sandraromanchenko** [comment]
@boris-ilijic it's just temporary hack, I won't merge it, so please ignore it for now)

**Comment by boris-ilijic** [comment]
Yes, in the meantime I deleted my question, because I noticed that pr is in draft. Didn't noticed it before, sorry for confusion ...

**Review by defbin — APPROVED** [review]
I am okay with this fix. However, filesystem and Azure Storage checks for leftover files need to be implemented. At present, I'd do this separately to not block this fix.

**Review by boris-ilijic — APPROVED** [review]
I guess that we have the Jira ticket for the missing feature.

**Pull request merged**
