### PR TITLE
Physical backups improvements

### PR DESCRIPTION
**Pull request by dAdAbird**
### Added new command `pbm describe-restore`
Outputs detailed information on the given restore.
```
$ pbm describe-restore 2022-08-03T09:25:54.4242858Z
name: "2022-08-03T09:25:54.4242858Z"
backup: "2022-07-28T12:10:13Z"
type: logical
status: done
replsets:
- name: rs1
  status: done
  last_transition_time: "2022-08-03T09:26:02Z"
- name: cfg
  status: done
  last_transition_time: "2022-08-03T09:26:03Z"
- name: rs2
  status: done
  last_transition_time: "2022-08-03T09:26:03Z"
opid: 62ea3f2202ad53f3e9e8ea59
start: "2022-08-03T09:25:54Z"
last_transition_time: "2022-08-03T09:26:04Z"
```
It also has a flag `-c` (`--config`) which **works only with physical restores**. It allows pointing a pbm config so PBM can read restore status on storage (mongod during physical restore is down). Example: `pbm describe-restore -c /etc/pbm/conf.yaml 2022-08-02T18:50:35.1889332Z`

### Use restore name instead of backup's name
In a number of places (`pbm list --restore`, `pbm logs`) restore was identified bu the backup's name. Which is inconvenient as we may have multiple restores from the same backup. 
Now rather the restore name is used everywhere. `pbm restore` also is displaying the restore name. 

### Consider WiredTiger options during the restore ([PBM-909](https://github.com/percona/percona-backup-mongodb/pull/686/commits/bc76279ec80232dc5784a39b44f7ff93372464a2))
During physical backup, store a WT config in the backup's meta. The restore will apply that config during internal temporary mongod starts.

## Physical restores

- Improved tmp port peeking.
- Agents send heartbeats via storage.  Hence pbm is aware of system longevity during restore. ([PBM-813](https://jira.percona.com/browse/PBM-813))
- Improved agents' sync and error reporting.
- Internal tmp mongod starts now write logs to `pbm.restore.log` inside dbpath. This file is removed after the restore only if it's finished successfully. ([PBM-898](https://jira.percona.com/browse/PBM-898), [PBM-812](https://jira.percona.com/browse/PBM-812)) 

Fixes https://jira.percona.com/browse/PBM-813
Fixes https://jira.percona.com/browse/PBM-898, https://jira.percona.com/browse/PBM-812
Fixes https://jira.percona.com/browse/PBM-909

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| New cluster psmdb 4.4 | passed | - |
| New cluster psmdb 4.2 | passed | - |
| Sharded psmdb 4.2 | passed | failed |
| Sharded psmdb 4.4 | passed | passed |
| Sharded psmdb 5.0 | failed | passed |
| New cluster psmdb 5.0 | passed | - |
| Non-sharded psmdb 4.2 | failed | passed |
| Non-sharded psmdb 4.4 | passed | passed |
| Single-node psmdb 4.4 | failed | passed |
| Single-node psmdb 4.2 | failed | passed |
| Single-node psmdb 5.0 | passed | passed |
| Non-sharded psmdb 5.0 | passed | passed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| Sharded psmdb 4.2 | failed | passed |
| Sharded psmdb 4.4 | failed | passed |
| Sharded psmdb 5.0 | failed | passed |
| New cluster psmdb 4.2 | passed | - |
| New cluster psmdb 4.4 | passed | - |
| New cluster psmdb 5.0 | failed | - |
| Non-sharded psmdb 4.2 | passed | passed |
| Non-sharded psmdb 4.4 | passed | passed |
| Non-sharded psmdb 5.0 | passed | passed |
| Single-node psmdb 4.2 | passed | passed |
| Single-node psmdb 4.4 | failed | passed |
| Single-node psmdb 5.0 | passed | passed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| New cluster psmdb 4.2 | failed | - |
| Sharded psmdb 5.0 | failed | passed |
| Sharded psmdb 4.4 | failed | passed |
| Sharded psmdb 4.2 | failed | failed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| Sharded psmdb 4.2 | failed | passed |
| Sharded psmdb 4.4 | failed | passed |
| Sharded psmdb 5.0 | failed | failed |
| New cluster psmdb 4.2 | failed | - |
| New cluster psmdb 4.4 | passed | - |
| New cluster psmdb 5.0 | passed | - |
| Non-sharded psmdb 4.2 | failed | passed |
| Non-sharded psmdb 5.0 | failed | passed |
| Non-sharded psmdb 4.4 | failed | failed |
| Single-node psmdb 5.0 | failed | passed |
| Single-node psmdb 4.2 | failed | passed |
| Single-node psmdb 4.4 | failed | passed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| Sharded psmdb 4.2 | failed | failed |
| Sharded psmdb 4.4 | failed | failed |
| New cluster psmdb 4.2 | passed | - |
| Sharded psmdb 5.0 | failed | failed |
| New cluster psmdb 4.4 | passed | - |
| New cluster psmdb 5.0 | failed | - |
| Non-sharded psmdb 4.2 | failed | failed |
| Non-sharded psmdb 4.4 | failed | failed |
| Non-sharded psmdb 5.0 | failed | failed |
| Single-node psmdb 4.2 | failed | failed |
| Single-node psmdb 4.4 | failed | failed |
| Single-node psmdb 5.0 | failed | failed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| New cluster psmdb 4.2 | failed | - |
| Sharded psmdb 4.2 | failed | failed |
| Sharded psmdb 4.4 | failed | - |
| Sharded psmdb 5.0 | failed | - |
| New cluster psmdb 4.4 | passed | - |
| New cluster psmdb 5.0 | passed | - |
| Non-sharded psmdb 4.2 | failed | passed |
| Non-sharded psmdb 4.4 | failed | passed |
| Non-sharded psmdb 5.0 | failed | passed |
| Single-node psmdb 4.2 | failed | passed |
| Single-node psmdb 4.4 | failed | passed |
| Single-node psmdb 5.0 | failed | passed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| Sharded psmdb 4.2 | failed | passed |
| New cluster psmdb 4.4 | passed | - |
| New cluster psmdb 4.2 | failed | - |
| Sharded psmdb 4.4 | failed | passed |
| New cluster psmdb 5.0 | passed | - |
| Sharded psmdb 5.0 | failed | passed |
| Non-sharded psmdb 4.2 | failed | passed |
| Non-sharded psmdb 4.4 | failed | passed |
| Single-node psmdb 4.2 | failed | failed |
| Single-node psmdb 4.4 | failed | passed |
| Non-sharded psmdb 5.0 | failed | passed |
| Single-node psmdb 5.0 | failed | passed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| New cluster psmdb 4.2 | passed | - |
| Sharded psmdb 4.2 | failed | passed |
| Sharded psmdb 4.4 | failed | passed |
| Sharded psmdb 5.0 | failed | passed |
| New cluster psmdb 4.4 | passed | - |
| New cluster psmdb 5.0 | failed | - |
| Non-sharded psmdb 4.2 | failed | failed |
| Non-sharded psmdb 4.4 | failed | passed |
| Non-sharded psmdb 5.0 | failed | failed |
| Single-node psmdb 4.2 | failed | passed |
| Single-node psmdb 4.4 | failed | passed |
| Single-node psmdb 5.0 | failed | passed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| New cluster psmdb 4.2 | failed | - |
| New cluster psmdb 5.0 | failed | - |
| Non-sharded psmdb 4.2 | failed | failed |
| New cluster psmdb 4.4 | passed | - |
| Non-sharded psmdb 4.4 | failed | passed |
| Single-node psmdb 4.4 | failed | passed |
| Non-sharded psmdb 5.0 | failed | failed |
| Single-node psmdb 4.2 | failed | failed |
| Single-node psmdb 5.0 | failed | failed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| New cluster psmdb 4.2 | passed | - |
| Sharded psmdb 4.2 | failed | passed |
| Sharded psmdb 4.4 | failed | passed |
| Sharded psmdb 5.0 | failed | passed |
| New cluster psmdb 4.4 | passed | - |
| New cluster psmdb 5.0 | passed | - |
| Non-sharded psmdb 4.2 | failed | passed |
| Non-sharded psmdb 4.4 | failed | passed |
| Single-node psmdb 4.4 | failed | passed |
| Single-node psmdb 4.2 | failed | passed |
| Non-sharded psmdb 5.0 | failed | passed |
| Single-node psmdb 5.0 | failed | passed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| Sharded psmdb 4.4 | passed | passed |
| Sharded psmdb 5.0 | failed | passed |
| Sharded psmdb 4.2 | passed | passed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| New cluster psmdb 4.2 | failed | - |
| Sharded psmdb 4.2 | failed | failed |
| Sharded psmdb 4.4 | failed | failed |
| Sharded psmdb 5.0 | failed | failed |
| New cluster psmdb 4.4 | passed | - |
| New cluster psmdb 5.0 | passed | - |
| Non-sharded psmdb 4.2 | failed | passed |
| Non-sharded psmdb 4.4 | failed | passed |
| Non-sharded psmdb 5.0 | failed | passed |
| Single-node psmdb 4.2 | failed | passed |
| Single-node psmdb 5.0 | failed | passed |
| Single-node psmdb 4.4 | failed | passed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| Sharded psmdb 4.2 | failed | passed |
| New cluster psmdb 4.2 | failed | - |
| New cluster psmdb 4.4 | passed | - |
| Sharded psmdb 4.4 | passed | passed |
| Sharded psmdb 5.0 | passed | failed |
| New cluster psmdb 5.0 | failed | - |
| Non-sharded psmdb 4.2 | failed | passed |
| Non-sharded psmdb 4.4 | failed | failed |
| Non-sharded psmdb 5.0 | passed | failed |
| Single-node psmdb 4.2 | passed | passed |
| Single-node psmdb 5.0 | passed | passed |
| Single-node psmdb 4.4 | passed | passed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| Non-sharded psmdb 4.2 | passed | failed |
| New cluster psmdb 4.4 | passed | - |
| New cluster psmdb 5.0 | passed | - |
| New cluster psmdb 4.2 | failed | - |
| Sharded psmdb 4.4 | passed | failed |
| Sharded psmdb 4.2 | failed | failed |
| Sharded psmdb 5.0 | failed | failed |
| Non-sharded psmdb 4.4 | failed | failed |
| Non-sharded psmdb 5.0 | failed | failed |
| Single-node psmdb 4.2 | failed | failed |
| Single-node psmdb 5.0 | passed | failed |
| Single-node psmdb 4.4 | passed | failed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| Sharded psmdb 4.2 | failed | passed |
| Sharded psmdb 4.4 | failed | failed |
| Sharded psmdb 5.0 | failed | passed |
| New cluster psmdb 4.2 | passed | - |
| New cluster psmdb 4.4 | passed | - |
| New cluster psmdb 5.0 | failed | - |
| Non-sharded psmdb 4.4 | passed | failed |
| Non-sharded psmdb 4.2 | failed | passed |
| Non-sharded psmdb 5.0 | passed | failed |
| Single-node psmdb 4.2 | failed | failed |
| Single-node psmdb 4.4 | passed | failed |
| Single-node psmdb 5.0 | passed | failed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| Sharded psmdb 4.2 | failed | failed |
| New cluster psmdb 4.2 | passed | - |
| New cluster psmdb 5.0 | failed | - |
| New cluster psmdb 4.4 | passed | - |
| Non-sharded psmdb 4.2 | passed | passed |
| Non-sharded psmdb 4.4 | passed | passed |
| Non-sharded psmdb 5.0 | passed | failed |
| Single-node psmdb 4.2 | passed | passed |
| Single-node psmdb 4.4 | passed | passed |
| Single-node psmdb 5.0 | passed | failed |
| Sharded psmdb 4.4 | failed | failed |
| Sharded psmdb 5.0 | failed | failed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| New cluster psmdb 4.2 | passed | - |
| Sharded psmdb 4.2 | failed | failed |
| New cluster psmdb 4.4 | passed | - |
| New cluster psmdb 5.0 | failed | - |
| Non-sharded psmdb 4.2 | passed | passed |
| Single-node psmdb 4.2 | passed | failed |
| Non-sharded psmdb 4.4 | passed | passed |
| Non-sharded psmdb 5.0 | failed | passed |
| Single-node psmdb 4.4 | passed | failed |
| Single-node psmdb 5.0 | passed | failed |
| Sharded psmdb 4.4 | failed | failed |
| Sharded psmdb 5.0 | failed | failed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| New cluster psmdb 4.2 | passed | - |
| New cluster psmdb 4.4 | passed | - |
| Sharded psmdb 4.2 | failed | failed |
| Sharded psmdb 4.4 | failed | failed |
| New cluster psmdb 5.0 | passed | - |
| Non-sharded psmdb 4.2 | failed | passed |
| Non-sharded psmdb 4.4 | passed | failed |
| Non-sharded psmdb 5.0 | failed | passed |
| Single-node psmdb 4.2 | passed | passed |
| Single-node psmdb 4.4 | passed | passed |
| Single-node psmdb 5.0 | failed | failed |
| Sharded psmdb 5.0 | failed | failed |

**Review by defbin — APPROVED** [review]
lgtm

**Pull request merged**
