### PR TITLE
[PBM-1196] Allow member tags to be used in backup priority calculation

### PR DESCRIPTION
**Pull request by tauffredou**
Issue https://jira.percona.com/browse/PBM-1196

Current priority can be defined as either 
- dynamically using member role in the replicaset
- statically using member host name

This PR uses member tags to define another priority selector

example: the member `node3` has the tag  `nodeType: "BACKUP" `
<details>
<summary>Replicaset config</summary>

```{
  _id: 'rs0',
  members: [
    {
      _id: 0,
      host: 'node1:27017',
      arbiterOnly: false,
      buildIndexes: true,
      hidden: false,
      priority: 1,
      tags: {},
      secondaryDelaySecs: Long("0"),
      votes: 1
    },
    {
      _id: 1,
      host: 'node2:27017',
      arbiterOnly: false,
      buildIndexes: true,
      hidden: false,
      priority: 1,
      tags:  {},
      secondaryDelaySecs: Long("0"),
      votes: 1
    },
    {
      _id: 2,
      host: 'node3:27017',
      arbiterOnly: false,
      buildIndexes: true,
      hidden: false,
      priority: 1,
      tags:  { nodeType: "BACKUP" },
      secondaryDelaySecs: Long("0"),
      votes: 1
    }
  ]
}
```

</details>

With the following configuration `node3` would get a score of **5**

```
  backup:
    priority:
      "tag:nodeType:BACKUP": 5
```

status: 
- [x] unit tests
- [ ] integration tests

### CODE REVIEW

**Comment by defbin** [comment]
Hi @tauffredou 

Thank you for your contribution.

Could you please create a [JIRA Ticket](https://jira.percona.com/) with a description of what you are trying to do from an end-user point of view?

**Comment by tauffredou** [comment]
issue https://jira.percona.com/browse/PBM-1196

**Comment by defbin** [comment]
it is a local build image. pls take a look at the fix https://github.com/percona/percona-backup-mongodb/pull/890

**Comment by capri1989** [comment]
Hi @tauffredou,

as this PR has been stale for almost 6 months, I would like to close here, and we can reopen any time or create a new one if you reconsider working on this feature.

We currently do not have this feature/improvement on our roadmap, as our users haven't requested this of far.

If you still think this would be a useful enhancement, and you can manage to develop the change and all the testing, etc. we can reconsider and talk about it.

Again, thanks a lot, but closing here for now.

**Pull request closed without merging**
