### PR TITLE
Fix physical backup tests

### PR DESCRIPTION
**Pull request by dAdAbird**
Unlike with the logical backups, the LastWrite of physical once
"happening" in seconds after the backup start. So, in tests, we should
wait before committing the first transaction.

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| Sharded psmdb 4.2 | failed | failed |
| Sharded psmdb 4.4 | failed | passed |
| New cluster psmdb 4.2 | passed | - |
| Sharded psmdb 5.0 | failed | passed |
| New cluster psmdb 4.4 | passed | - |
| Non-sharded psmdb 4.2 | failed | failed |
| Non-sharded psmdb 4.4 | failed | passed |
| New cluster psmdb 5.0 | passed | - |
| Single-node psmdb 4.4 | failed | passed |
| Non-sharded psmdb 5.0 | failed | passed |
| Single-node psmdb 4.2 | failed | passed |
| Single-node psmdb 5.0 | failed | passed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| Sharded psmdb 4.2 | failed | failed |
| Sharded psmdb 4.4 | failed | passed |
| Sharded psmdb 5.0 | failed | passed |
| New cluster psmdb 4.4 | passed | - |
| New cluster psmdb 4.2 | passed | - |
| New cluster psmdb 5.0 | passed | - |
| Non-sharded psmdb 4.2 | failed | failed |
| Non-sharded psmdb 4.4 | failed | failed |
| Non-sharded psmdb 5.0 | failed | failed |
| Single-node psmdb 4.2 | failed | passed |
| Single-node psmdb 4.4 | failed | passed |
| Single-node psmdb 5.0 | failed | passed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| New cluster psmdb 4.2 | passed | - |
| Sharded psmdb 4.2 | failed | failed |
| Sharded psmdb 4.4 | failed | passed |
| Sharded psmdb 5.0 | failed | passed |
| New cluster psmdb 4.4 | passed | - |
| New cluster psmdb 5.0 | passed | - |
| Non-sharded psmdb 4.2 | failed | failed |
| Single-node psmdb 4.2 | failed | failed |
| Non-sharded psmdb 4.4 | failed | failed |
| Single-node psmdb 4.4 | failed | passed |
| Single-node psmdb 5.0 | failed | passed |
| Non-sharded psmdb 5.0 | failed | passed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| Sharded psmdb 4.2 | passed | failed |
| New cluster psmdb 4.2 | passed | - |
| Sharded psmdb 5.0 | failed | passed |
| New cluster psmdb 4.4 | passed | - |
| Sharded psmdb 4.4 | passed | passed |
| New cluster psmdb 5.0 | passed | - |
| Non-sharded psmdb 4.4 | passed | passed |
| Non-sharded psmdb 4.2 | passed | failed |
| Non-sharded psmdb 5.0 | failed | passed |
| Single-node psmdb 4.2 | passed | passed |
| Single-node psmdb 5.0 | failed | passed |
| Single-node psmdb 4.4 | passed | passed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| Sharded psmdb 4.2 | passed | failed |
| Sharded psmdb 4.4 | passed | passed |
| Sharded psmdb 5.0 | failed | passed |
| New cluster psmdb 4.2 | passed | - |
| New cluster psmdb 4.4 | passed | - |
| New cluster psmdb 5.0 | passed | - |
| Non-sharded psmdb 4.2 | failed | failed |
| Non-sharded psmdb 4.4 | passed | passed |
| Non-sharded psmdb 5.0 | failed | passed |
| Single-node psmdb 4.2 | passed | passed |
| Single-node psmdb 4.4 | passed | passed |
| Single-node psmdb 5.0 | failed | passed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| Sharded psmdb 4.4 | passed | passed |
| Sharded psmdb 4.2 | passed | passed |
| Sharded psmdb 5.0 | failed | passed |
| New cluster psmdb 4.2 | passed | - |
| New cluster psmdb 4.4 | passed | - |
| Non-sharded psmdb 4.2 | failed | passed |
| New cluster psmdb 5.0 | passed | - |
| Non-sharded psmdb 4.4 | passed | passed |
| Single-node psmdb 4.2 | passed | passed |
| Single-node psmdb 4.4 | passed | passed |
| Single-node psmdb 5.0 | failed | passed |
| Non-sharded psmdb 5.0 | failed | passed |

**Review by defbin — APPROVED** [review]

**Pull request merged**
