### PR TITLE
PBM-488: Method to influence which pbm-agent node will do backups

### PR DESCRIPTION
**Pull request by dAdAbird**
Design doc: https://docs.google.com/document/d/1x8TK7OWSj9DlM_6fP7RXWtzxYS-CP3PHN4GT6m8X5DM

Config example:
```
backup:
  priority:
    "localhost:28019": 2.5
    "localhost:37028": 2.5
    "localhost:37029": 2.0
    "localhost:37019": 0.1
```

https://jira.percona.com/browse/PBM-488

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| mongodb 3.6 | failed |
| mongodb 4.0 | failed |
| mongodb 4.2 | failed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| mongodb 3.6 | failed |
| mongodb 4.0 | failed |
| mongodb 4.2 | failed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| mongodb 3.6 | failed |
| mongodb 4.0 | failed |
| mongodb 4.2 | failed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| mongodb 4.2 | failed |
| mongodb 3.6 | failed |
| mongodb 4.0 | failed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| mongodb 3.6 | failed |
| mongodb 4.0 | failed |
| mongodb 4.2 | failed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| mongodb 3.6 | passed |
| mongodb 4.0 | failed |
| mongodb 4.2 | failed |

**Review by akira-kurogane — APPROVED** [review]
LGTM

**Pull request merged**
