### PR TITLE
Fix physical bcp tests

### PR DESCRIPTION
**Pull request by dAdAbird**
"Physical" tests were in fact running logical once due to respective env var was set after docker build. It fixes this.

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| Sharded psmdb 4.2 | failed | failed |
| Sharded psmdb 4.4 | failed | failed |
| Sharded psmdb 5.0 | failed | failed |
| Non-sharded psmdb 4.2 | failed | failed |
| New cluster psmdb 4.2 | passed | - |
| Non-sharded psmdb 4.4 | failed | failed |
| Single-node psmdb 4.2 | failed | failed |
| New cluster psmdb 4.4 | passed | - |
| Single-node psmdb 4.4 | failed | failed |
| New cluster psmdb 5.0 | passed | - |
| Non-sharded psmdb 5.0 | failed | failed |
| Single-node psmdb 5.0 | failed | failed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| Sharded psmdb 4.2 | failed | failed |
| Sharded psmdb 4.4 | failed | failed |
| Sharded psmdb 5.0 | failed | failed |
| Non-sharded psmdb 5.0 | failed | failed |
| Non-sharded psmdb 4.2 | failed | failed |
| New cluster psmdb 4.4 | passed | - |
| New cluster psmdb 4.2 | passed | - |
| Single-node psmdb 4.4 | failed | failed |
| Single-node psmdb 4.2 | failed | failed |
| Non-sharded psmdb 4.4 | failed | failed |
| Single-node psmdb 5.0 | failed | failed |
| New cluster psmdb 5.0 | failed | - |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| Sharded psmdb 4.2 | failed | failed |
| Sharded psmdb 4.4 | failed | failed |
| Sharded psmdb 5.0 | failed | failed |
| Non-sharded psmdb 4.2 | failed | failed |
| Non-sharded psmdb 4.4 | failed | failed |
| New cluster psmdb 4.2 | passed | - |
| New cluster psmdb 4.4 | passed | - |
| Single-node psmdb 4.2 | failed | - |
| New cluster psmdb 5.0 | passed | - |
| Single-node psmdb 4.4 | failed | - |
| Non-sharded psmdb 5.0 | failed | failed |
| Single-node psmdb 5.0 | failed | - |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| Sharded psmdb 4.4 | failed | failed |
| Sharded psmdb 5.0 | failed | failed |
| Sharded psmdb 4.2 | failed | failed |
| Single-node psmdb 4.4 | failed | failed |
| Single-node psmdb 5.0 | failed | failed |
| Non-sharded psmdb 4.2 | failed | failed |
| Single-node psmdb 4.2 | failed | failed |
| New cluster psmdb 4.4 | failed | - |
| Non-sharded psmdb 4.4 | failed | failed |
| Non-sharded psmdb 5.0 | failed | failed |
| New cluster psmdb 4.2 | failed | - |
| New cluster psmdb 5.0 | failed | - |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| New cluster psmdb 4.2 | passed | - |
| Sharded psmdb 4.2 | failed | failed |
| Sharded psmdb 4.4 | failed | failed |
| Sharded psmdb 5.0 | failed | failed |
| New cluster psmdb 4.4 | passed | - |
| New cluster psmdb 5.0 | passed | - |
| Non-sharded psmdb 4.2 | failed | failed |
| Non-sharded psmdb 5.0 | failed | passed |
| Non-sharded psmdb 4.4 | failed | passed |
| Single-node psmdb 4.4 | failed | passed |
| Single-node psmdb 4.2 | failed | passed |
| Single-node psmdb 5.0 | failed | failed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| Sharded psmdb 4.4 | failed | failed |
| Sharded psmdb 4.2 | failed | failed |
| New cluster psmdb 5.0 | failed | - |
| New cluster psmdb 4.4 | failed | - |
| Non-sharded psmdb 5.0 | failed | failed |
| New cluster psmdb 4.2 | failed | - |
| Non-sharded psmdb 4.2 | failed | failed |
| Non-sharded psmdb 4.4 | failed | failed |
| Sharded psmdb 5.0 | failed | failed |
| Single-node psmdb 4.2 | failed | - |
| Single-node psmdb 4.4 | failed | - |
| Single-node psmdb 5.0 | failed | - |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| Sharded psmdb 4.2 | failed | failed |
| Sharded psmdb 4.4 | passed | failed |
| New cluster psmdb 5.0 | passed | - |
| Non-sharded psmdb 4.2 | passed | failed |
| New cluster psmdb 4.4 | failed | - |
| Non-sharded psmdb 4.4 | failed | failed |
| Sharded psmdb 5.0 | failed | failed |
| New cluster psmdb 4.2 | failed | - |
| Single-node psmdb 5.0 | failed | failed |
| Non-sharded psmdb 5.0 | failed | passed |
| Single-node psmdb 4.2 | failed | failed |
| Single-node psmdb 4.4 | failed | failed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| Sharded psmdb 4.2 | passed | failed |
| Sharded psmdb 4.4 | passed | failed |
| New cluster psmdb 4.2 | passed | - |
| Sharded psmdb 5.0 | failed | failed |
| New cluster psmdb 4.4 | passed | - |
| New cluster psmdb 5.0 | failed | - |
| Non-sharded psmdb 4.2 | passed | passed |
| Non-sharded psmdb 4.4 | passed | passed |
| Non-sharded psmdb 5.0 | failed | passed |
| Single-node psmdb 4.4 | passed | passed |
| Single-node psmdb 5.0 | failed | passed |
| Single-node psmdb 4.2 | passed | passed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| Sharded psmdb 4.2 | passed | failed |
| Sharded psmdb 4.4 | passed | failed |
| Sharded psmdb 5.0 | failed | failed |
| New cluster psmdb 4.4 | passed | - |
| New cluster psmdb 5.0 | passed | - |
| New cluster psmdb 4.2 | passed | - |
| Non-sharded psmdb 4.2 | failed | failed |
| Non-sharded psmdb 4.4 | failed | passed |
| Single-node psmdb 4.2 | passed | passed |
| Single-node psmdb 4.4 | passed | passed |
| Non-sharded psmdb 5.0 | failed | passed |
| Single-node psmdb 5.0 | failed | failed |

**Review by defbin — APPROVED** [review]

**Pull request merged**
