### PR TITLE
Release 1.5.0

### PR DESCRIPTION
**Pull request by vorsel**

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| Sharded cluster mongodb 3.6 | passed |
| Sharded cluster mongodb 4.0 | passed |
| Sharded cluster mongodb 4.2 | passed |
| Restore on new cluster mongodb 3.6 | passed |
| Restore on new cluster mongodb 4.0 | passed |
| Non-sharded replicaset mongodb 3.6 | passed |
| Restore on new cluster mongodb 4.2 | passed |
| Non-sharded replicaset mongodb 4.0 | passed |
| Non-sharded replicaset mongodb 4.2 | passed |
| Single-node replicaset mongodb 4.0 | passed |
| Single-node replicaset mongodb 3.6 | passed |
| Single-node replicaset mongodb 4.2 | passed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| Sharded cluster mongodb 3.6 | passed |
| Sharded cluster mongodb 4.0 | passed |
| Sharded cluster mongodb 4.2 | passed |
| Restore on new cluster mongodb 3.6 | passed |
| Restore on new cluster mongodb 4.0 | passed |
| Non-sharded replicaset mongodb 3.6 | passed |
| Restore on new cluster mongodb 4.2 | passed |
| Non-sharded replicaset mongodb 4.0 | passed |
| Non-sharded replicaset mongodb 4.2 | passed |
| Single-node replicaset mongodb 3.6 | passed |
| Single-node replicaset mongodb 4.0 | failed |
| Single-node replicaset mongodb 4.2 | passed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| Sharded cluster mongodb 3.6 | failed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| Restore on new cluster mongodb 3.6 | passed |
| Restore on new cluster mongodb 4.0 | passed |
| Restore on new cluster mongodb 4.2 | passed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| Sharded cluster mongodb 3.6 | passed |
| Sharded cluster mongodb 4.2 | passed |
| Sharded cluster mongodb 4.0 | passed |
| Non-sharded replicaset mongodb 4.2 | failed |
| Single-node replicaset mongodb 3.6 | passed |
| Non-sharded replicaset mongodb 3.6 | passed |
| Non-sharded replicaset mongodb 4.0 | passed |
| Restore on new cluster mongodb 3.6 | passed |
| Restore on new cluster mongodb 4.0 | passed |
| Restore on new cluster mongodb 4.2 | passed |
| Single-node replicaset mongodb 4.2 | passed |
| Single-node replicaset mongodb 4.0 | passed |

**Comment by defbin** [comment]
@dAdAbird, should we close the PR?

**Pull request closed without merging**
