### PR TITLE
[PBM-810] rename backups files in e2e-tests/

### PR DESCRIPTION
**Pull request by defbin**

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| New cluster psmdb 4.2 | passed | - |
| Sharded psmdb 4.2 | passed | passed |
| Sharded psmdb 4.4 | failed | failed |
| Sharded psmdb 5.0 | failed | failed |
| Non-sharded psmdb 4.2 | failed | passed |
| Non-sharded psmdb 4.4 | failed | failed |
| New cluster psmdb 4.4 | passed | - |
| New cluster psmdb 5.0 | passed | - |
| Single-node psmdb 4.2 | failed | passed |
| Single-node psmdb 4.4 | failed | passed |
| Non-sharded psmdb 5.0 | failed | failed |
| Single-node psmdb 5.0 | failed | failed |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| New cluster psmdb 4.2 | passed | - |
| Sharded psmdb 4.2 | passed | passed |
| Sharded psmdb 4.4 | failed | failed |
| Sharded psmdb 5.0 | failed | - |
| Single-node psmdb 4.2 | passed | passed |
| Non-sharded psmdb 4.2 | passed | passed |
| Single-node psmdb 4.4 | passed | passed |
| Non-sharded psmdb 4.4 | passed | passed |
| New cluster psmdb 4.4 | passed | - |
| Single-node psmdb 5.0 | failed | failed |
| Non-sharded psmdb 5.0 | failed | failed |
| New cluster psmdb 5.0 | passed | - |

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| New cluster psmdb 4.2 | passed | - |
| New cluster psmdb 4.4 | passed | - |
| Non-sharded psmdb 4.2 | failed | failed |
| Sharded psmdb 4.4 | passed | failed |
| Sharded psmdb 4.2 | passed | failed |
| Sharded psmdb 5.0 | failed | failed |
| New cluster psmdb 5.0 | passed | - |
| Non-sharded psmdb 5.0 | failed | passed |
| Non-sharded psmdb 4.4 | passed | passed |
| Single-node psmdb 4.4 | passed | passed |
| Single-node psmdb 5.0 | failed | passed |
| Single-node psmdb 4.2 | passed | failed |

**Review by dAdAbird — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| Sharded psmdb 4.2 | failed | failed |
| Sharded psmdb 4.4 | failed | failed |
| New cluster psmdb 4.4 | passed | - |
| New cluster psmdb 4.2 | passed | - |
| Sharded psmdb 5.0 | failed | failed |
| New cluster psmdb 5.0 | passed | - |
| Non-sharded psmdb 4.2 | passed | failed |
| Non-sharded psmdb 4.4 | failed | passed |
| Non-sharded psmdb 5.0 | failed | passed |
| Single-node psmdb 4.2 | passed | passed |
| Single-node psmdb 5.0 | failed | passed |
| Single-node psmdb 4.4 | passed | passed |

**Pull request merged**
